name: SMSpp_builder
channels:
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib

  # for the exercises on pypsa
  - pypsa
  - glpk
  - gurobi  # not necessary but can ease the usability for some users

  # for jupyter
  - jupyter
  - ipython
  - ipykernel
 
- pip:
  - git+https://github.com/davide-f/google-drive-downloader@disable_print  # google drive with fix for virus scan